Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods:
    - let
    - it
    - describe
    - context
    - specify
    - define

Metrics/MethodLength:
  Max: 25
  Exclude:
    - spec/db_helper.rb

AllCops:
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 16
  Exclude:
    - spec/db_helper.rb

Metrics/ClassLength:
  Max: 125
