AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 100
  Exclude:
    - spec/dbee/providers/active_record_provider/makers/where_spec.rb

Metrics/AbcSize:
  Max: 17
  Exclude:
    - spec/db_helper.rb

Metrics/BlockLength:
  ExcludedMethods:
    - let
    - it
    - describe
    - context
    - specify
    - define
  Exclude:
    - spec/dbee/**/*
    - dbee-active_record.gemspec

Metrics/ClassLength:
  Max: 140

Metrics/MethodLength:
  Max: 25
  Exclude:
    - spec/db_helper.rb
